retargeting:
  type: position
  urdf_path: botyard_hand/botyard_hand_left.urdf

  target_joint_names: [
    # 前臂关节
    # "FAJ1", "FAJ3",
    # 食指关节
    "FFJ1", "FFJ2", "FFJ3", "FFJ4",
    # 小指关节
    "LFJ1", "LFJ2", "LFJ3", "LFJ4",
    # 中指关节
    "MFJ1", "MFJ2", "MFJ3", "MFJ4",
    # 无名指关节
    "RFJ1", "RFJ2", "RFJ3", "RFJ4",
    # 拇指关节
    "THJ1", "THJ2", "THJ3", "THJ4"
  ]
  # target_link_names: [ "thtip", "fftip", "mftip", "rftip", "lftip",
  #                      "thmiddle", "ffmiddle", "mfmiddle", "rfmiddle", "lfmiddle" ]


  target_link_names: [ "thtip", "fftip", "mftip", "rftip", "lftip",
                       "thmiddle", "ffmiddle", "mfmiddle", "rfmiddle", "lfmiddle" ]

  target_link_human_indices: [ 4, 8, 12, 16, 20, 2, 6, 10, 14, 18 ]
  add_dummy_free_joint: True

  # 优化参数
  # normal_delta: 0.1  # 增加关节角度约束权重
  # huber_delta: 0.05  # 增加位置约束的平滑度
  low_pass_alpha: 1  # 保持平滑滤波
